#!/bin/python3
import sys
import math

"""
base <integer>

Returns a representation of the passed integer in base 62.
"""

base="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

number=int(sys.argv[1])
result=[]
for power in range(int(math.log(number ,len(base))) + 1):
    result += [ base[ int(number/(len(base)**power)) % len(base) ] ]

result.reverse()

print("".join(result));
