#!/bin/bash

command -v oxipng >/dev/null 2>&1 && HAS_OXIPNG=1
command -v pngquant >/dev/null 2>&1 && HAS_PNGQUANT=1


ls *.ora *.kra 2>/dev/null | while read file; do
    [[ $file == *-autosave.kra ]] && continue
    pngout="${file%%.[ok]ra}.png"
    tifout="${file%%.[ok]ra}.tif"
    quantout="${file%%.[ok]ra}-fs8.png"
    if [[ "$pngout" -ot "$file" && "$tifout" -ot "$file" ]]; then
        echo "Rendering $file to $pngout"
        krita --export --export-filename "$pngout" "$file" > /dev/null 2>&1
        if [[ ! -f "$pngout" ]]; then
            # probably failed because of non-standard colour profile
            echo "Failed, trying $tifout"
            krita --export --export-filename "$tifout" "$file" > /dev/null 2>&1
        fi
    fi
    if [[ $HAS_OXIPNG == 1 && -f "$pngout" && $(wc -c < "$pngout") -ge 1000000 ]]; then
        echo "Crunching $pngout with oxipng"
        oxipng "$pngout"
    fi
    if [[ $HAS_PNGQUANT == 1 && -f "$pngout" && $(wc -c < "$pngout") -ge 1000000 && "$quantout" -ot "$file" ]]; then
        echo "Quantizing $pngout to $quantout"
        pngquant 256 -f "$pngout"
    fi
    if [[ -f "$pngout" ]]; then
        touch -r "$file" "$pngout"
    fi
    if [[ -f "$tifout" ]]; then
        touch -r "$file" "$tifout"
    fi
    if [[ -f "$quantout" ]]; then
        touch -r "$file" "$quantout"
    fi
done
