#!/bin/bash
ls *.ora *.kra 2>/dev/null | while read file; do
    out="${file%%.[ok]ra}.png"
    if [[ "$out" -ot "$file" ]]; then
        echo "Rendering $file to $out"
        krita --export --export-filename "$out" "$file" > /dev/null 2>&1
    fi
    if [[ -f "$out" ]]; then
        touch -r "$file" "$out"

        quantout="${file%%.[ok]ra}-fs8.png"
        if [[ $(wc -c < "$out") -ge 1000000 && "$quantout" -ot "$file" ]]; then
            echo "Quantizing $out to $quantout"
            pngquant 256 -f "$out"
        fi
        if [[ -f "$quantout" ]]; then
            touch -r "$file" "$quantout"
        fi

    fi
done
