#!/bin/bash

name="$(date -Ins | sed "y/,:T/--\//;s/+.*//").png"
file="$HOME/images/screenshots/${name}"
mkdir -p "$(dirname $file)"

if [[ $* == "-s" ]]; then
    maim -s -n --hidecursor $file
else
    maim $file
fi

if [[ ${file##*.} == "png" && $(stat -c %s "$file") -gt 500000 ]]; then
    jpeg="${file%.png}.jpeg"
    name="${name%.png}.jpeg"
    convert "$file" -quality 90 "$jpeg"
    file="$jpeg"
fi

rm -f /tmp/sscrot.*
ln -s $file /tmp/sscrot.${file##*.}

beep -l 20 -f 500 -n -l 10 -f 5000
up -temp $file $name
