#!/bin/bash

name="$(date -Is | sed "y/,:/--/;s/+.*//")-$(cat /dev/urandom | tr -cd "oO0" | head -c 4)"
file="$HOME/images/screenshots/${name}.png"
mkdir -p "$(dirname $file)"

if [[ $* == "-s" ]]; then
    maim -s -n --hidecursor $file
else
    maim $file
fi

if [[ ${file##*.} == "png" && $(stat -c %s "$file") -gt 500000 ]]; then
    jpeg="${file%.png}.jpeg"
    convert "$file" -quality 90 "$jpeg"
    file="$jpeg"
fi

rm -f /tmp/sscrot.*
ln -s $file /tmp/sscrot.${file##*.}

beep -l 20 -f 500 -n -l 10 -f 5000
up -24 $file
