#!/bin/bash

name="$(date -Ins | sed "y/,:/--/;s/+.*//")"
file="$HOME/images/screenshots/${name}.png"
mkdir -p "$(dirname $file)"
if [[ $* == "-g" ]]; then
    file="${file%.png}.gif"
    ffcast -s byzanz-record -- -c -d 6 --delay=1 $file
    gifsicle -O2 < $file > /tmp/.byzanz.gif
    mv /tmp/.byzanz.gif $file
elif [[ $* == "-v" ]]; then
    file="${file%.png}.webm"
    eval $(slop)
    ffmpeg -f x11grab -s ${W}x$H -i :0+$X,$Y -f alsa -i default -vcodec libvpx -vb 1600k -quality best -f webm -t 10 $file

elif [[ $* == "-s" ]]; then
    maim -s -n --hidecursor $file
else
    maim $file
fi

if [[ ${file##*.} == "png" && $(stat -c %s "$file") -gt 500000 ]]; then
    jpeg="${file%.png}.jpeg"
    convert "$file" -quality 90 "$jpeg"
    file="$jpeg"
fi

rm -f /tmp/sscrot.*
ln -s $file /tmp/sscrot.${file##*.}

beep -l 20 -f 500 -n -l 10 -f 5000
up -24 $file
