#!/bin/bash
# tamato
#
# a simple pomodoro timer for dzen and other bars

statefile="/tmp/$(basename $0)_${UID}"
touch $statefile
now=$(date +%s)

function status(){
    end=$(cat "$statefile")
    rgx='^[0-9]+$'
    [[ $end =~ $rgx ]] || end=0
    remaining=$[$end - $now]
    [[ $remaining -lt 0 ]] && remaining=0
    minutes=$[$remaining / 60]
    seconds=$[$remaining % 60]
    [[ ${#seconds} -lt 2 ]] && seconds="0$seconds"

    echo "$minutes:$seconds"
}

function start_pomodoro(){
    echo $[$now + (60*25)] > $statefile
}

function start_break(){
    echo $[$now + (60*5)] > $statefile
}

function start_long_break(){
    echo $[$now + (60*10)] > $statefile
}

function usage() {
    echo "$0 [-s|-b|-l]"
}

case $1 in
    "")
        status
        ;;
    "-s")
        start_pomodoro
        ;;
    "-b")
        start_break
        ;;
    "-l")
        start_long_break
        ;;
    *)
        usage
        exit 1
        ;;
esac
