#!/bin/bash

function upload(){
    [[ "$DIR" == "" ]] && DIR="$(date +%y%m)"
    [[ "$DEST" == "" ]] && DEST=$(basename "$SOURCE" | tr " \\/()[]\"&'%" '_')

    URL="https://codl-public.s3.amazonaws.com/$DIR/$DEST"

    if [[ -e /bin/xclip ]]; then
        printf "$URL" | xclip -i -selection primary 2> /dev/null
        printf "$URL" | xclip -i -selection clipboard 2> /dev/null
    fi

    if [[ -d "$SOURCE" ]]; then
        rclone copyto -e --exclude=".git/" "$SOURCE" "s3:codl-public/$DIR/$DEST"
    else
        rclone copyto -e "$SOURCE" "s3:codl-public/$DIR/$DEST"
    fi

    if [[ $? == 0 ]]; then
        echo "$URL"
        exit 0
    fi
}

function usage(){
    echo "Usage : up [-temp] [-root] <file> [destination]" > /dev/stderr
    exit 1
}

while true; do
    case $1 in
        "")
            usage
            ;;
        "-temp"|"-tmp"|"-24")
            DIR="temp"
            shift
            ;;
        "-root")
            DIR="/"
            shift
            ;;
        *)
            if [[ "$SOURCE" == "" ]]; then
                SOURCE=$1
            elif [[ "$DEST" == "" ]]; then
                DEST=$1
            else
                echo "Error: Too many arguments" > /dev/stderr
                usage
            fi
            shift
            [[ "$1" == "" ]] && upload
    esac
done

